### ISSUE TITLE
Delete image not working

### ISSUE THREAD

**Issue by lukasboomstra** [s1modev/media-upload#1]
The delete button svg does appear in the code but its not showing on the page. Now it's not possible to delete any added images. This also goes for the media upload demo

https://github.com/s1modev/media-upload-demo

**Comment by s1modev** [comment]
I tried to find the problem that you are describing, but every thing seems to work fine.
can you provide a screenshot of your problem...

**Comment by lukasboomstra** [comment]
Try to install a fresh installation of https://github.com/s1modev/media-upload-demo using `git clone https://github.com/s1modev/media-upload-demo.git` and follow the instructions:

composer install
npm install
npm run dev
php artisan key:generate
php artisan migrate:fresh
php artisan db:seed
php artisan optimize
php artisan serve

The following issue appears:
![Schermafbeelding 2022-01-11 om 13 09 51](https://user-images.githubusercontent.com/47446871/148940164-761de90e-2aaf-4339-8b95-91e105f3bc80.png)

![Schermafbeelding 2022-01-11 om 13 13 51](https://user-images.githubusercontent.com/47446871/148940699-fc43e9b0-c0b9-47aa-bace-8417c60d32a0.png)

How it should be as the gif in readme.md says:
![Schermafbeelding 2022-01-11 om 13 10 27](https://user-images.githubusercontent.com/47446871/148940230-fd18f987-46a7-4327-8ed7-07ac1d37167d.png)

**Comment by s1modev** [comment]
what browser are you using ?

**Comment by s1modev** [comment]
are you using google chrome ?

**Comment by s1modev** [comment]
what browser are you using ?

**Comment by lukasboomstra** [comment]
Ah yes, that's the issue. I am using safari. When I try Google Chrome it does indeed work.

**Comment by s1modev** [comment]
I will take care of it this week on the next commit. thanks for your feedback.

**Comment by s1modev** [comment]
this has nothing to do with this package.
I wrote about this situation in my [tutorial](https://dev.to/simodev/how-to-upload-multiple-images-with-preview-using-laravel-and-vue-282j)

>In the situation when a user upload the images on the form but leave the form before the final submit, the temporary images are still stored on the server and won't get moved or deleted.
well it’s up to you how to deal with this situation, but I recommend you to schedule an artisan command using Laravel scheduling to cleanup all those images that have not been used.

**Comment by lukasboomstra** [comment]
> this has nothing to do with this package. I wrote about this situation in my [tutorial](https://dev.to/simodev/how-to-upload-multiple-images-with-preview-using-laravel-and-vue-282j)
> 
> > In the situation when a user upload the images on the form but leave the form before the final submit, the temporary images are still stored on the server and won't get moved or deleted.
> > well it’s up to you how to deal with this situation, but I recommend you to schedule an artisan command using Laravel scheduling to cleanup all those images that have not been used.

Alright :)

**Comment by s1modev** [comment]
> Ah yes, that's the issue. I am using safari (14.1.2). When I try Google Chrome it does indeed work.

Did you try overriding the CSS ?

**Comment by s1modev** [comment]
> Ah yes, that's the issue. I am using safari (14.1.2). When I try Google Chrome it does indeed work.

Well I just knew that Safari works only on MACOS, and since I am a windows user I won't be able to test the changes.

Did you try overriding the package CSS ?

try to apply this CSS line : 
```
.times-icon{
    position: relative !important;
}
```

also try disabling your AdBlocker.
